### PR TITLE
Ensure each controller gets a globally unique ID

### PR DESCRIPTION
**Pull request by hbenl**

### CODE REVIEW

**Comment by connor4312** [comment]
Where were you hitting this, in a multi-root workspace? It's good to have controllers use the same label across reloads, otherwise results will get cleared on each reload.

**Comment by hbenl** [comment]
Yes, this was an issue in a multi-root workspace - Test Explorer doesn't have the requirement that the root suite labels are unique and in fact I think most adapters don't have unique labels for their root suites.

> It's good to have controllers use the same label across reloads, otherwise results will get cleared on each reload.

Ah, yes, I understand. In that case it probably makes sense to use both the root suite label (to distinguish between adapters from different extensions for the same workspace) and the path of the workspace folder (to distinguish between adapters from the same extension for different workspaces).

**Comment by connor4312** [comment]
Ok, cool. Would you like to make that change in this PR, or shall I stick it in?

**Comment by hbenl** [comment]
I just did.

**Comment by connor4312** [comment]
Perfect 🙂 I'll publish later today

**Pull request merged**
